### ISSUE TITLE
does compose testing support google maps?

### ISSUE THREAD

**Issue by GhiathAlbawab0** [googlemaps/android-maps-compose#126]
how to get the map in testing? and how to make sure loading completed in testing? any help please

**Comment by barbeau** [comment]
@GhiathAlbawab0 You can see an example of how UI tests can be written in the sample app in this repo:
https://github.com/googlemaps/android-maps-compose/blob/main/app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt

Please take a look at those and let me know if you have any questions.
