### ISSUE TITLE
Preview for GoogleMap Composable

### ISSUE THREAD

**Issue by ekotyoo** [googlemaps/android-maps-compose#128]
![Screenshot 2022-05-25 235552](https://user-images.githubusercontent.com/70650963/170318804-3d3dc3e7-9399-48a9-8bae-7ce198619f9e.png)
I thought there was an issue with my Android Studio, but when I try to render a preview for my UI that has `GoogleMap` composable, it literally shows only a blank preview. It is so difficult working on a UI that has `GoogleMap `composable in it, since I have to build my app to the emulator to see how my UI looks like with the map. 

It'd be helpful if we could see a preview of our map view even if it is only a static map.

**Comment by arriolac** [comment]
A similar strategy to https://github.com/google/accompanist/pull/1190 can be implemented here. Note, however, that still won't render a map on the preview but at least it wouldn't break your preview esp. if you had other contents.
