### ISSUE TITLE
GoogleMap - throwing exception No static method isTraceInProgress() on creation

### ISSUE THREAD

**Issue by newmanw** [googlemaps/android-maps-compose#132]
Android SDK 32
implementation 'com.google.maps.android:maps-compose:2.1.1'
implementation 'com.google.maps.android:maps-ktx:3.2.1'
implementation 'com.google.android.gms:play-services-maps:18.0.2'

When adding a google map:
```
Box(Modifier.fillMaxWidth().height(200.dp)) {
  GoogleMap {
  }
}
```

The following exception is thrown:

```
2022-05-29 11:25:43.068 7068-7068/com.test/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.app, PID: 7068
    java.lang.NoSuchMethodError: No static method isTraceInProgress()Z in class Landroidx/compose/runtime/ComposerKt; or its super classes (declaration of 'androidx.compose.runtime.ComposerKt' appears in /data/app/~~XD2sjyOaEipBqqf6GjSbvg==/com.test.app-ipMwN6R8eShn1COKo-3qbQ==/base.apk)
        at com.google.maps.android.compose.GoogleMapKt.GoogleMap(Unknown Source:6)
```

**Comment by barbeau** [comment]
@newmanw Thanks for the report!

What version of Jetpack Compose are you using? You'll need `1.2.x` of Compose with Maps Compose 1.3.0 and up.

**Comment by arqlz** [comment]
Im using 1.2.0-beta02, still no luck

  ext.kotlin_version = '1.6.10'
  ext.compose_version = "1.2.0-beta02"

  implementation 'com.google.maps.android:maps-compose:2.5.0'
  implementation 'com.google.android.gms:play-services-maps:18.0.2'

No static method isTraceInProgress()Z in class Landroidx/compose/runtime/ComposerKt; or its super classes (declaration of 'androidx.compose.runtime.ComposerKt' appears in ....

**Comment by thekingrenz23** [comment]
> Im using 1.2.0-beta02, still no luck
> 
> ```
>   ext.kotlin_version = '1.6.10'
>   ext.compose_version = "1.2.0-beta02"
> 
>   implementation 'com.google.maps.android:maps-compose:2.5.0'
>   implementation 'com.google.android.gms:play-services-maps:18.0.2'
> ```
> 
> **No static method isTraceInProgress()Z in class Landroidx/compose/runtime/ComposerKt; or its super classes (declaration of 'androidx.compose.runtime.ComposerKt' appears in ....**

I am using 1.2.0-rc01 try that one out
