### ISSUE TITLE
Add ability to use values from OnCameraMoveStartedListener callback

### ISSUE THREAD

**Issue by egorikftp** [googlemaps/android-maps-compose#144]
Hello, I have a case right now, that I need to detect if user start gesture on map during navigation. 

In this case I decided to use following callback:
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnCameraMoveStartedListener

In maps-compose implementation a see that you ignore Int values from callback and just set 'true'.

https://github.com/googlemaps/android-maps-compose/blob/e4e6796fc8d3cc7f3bd6b57db27d2dec79ba13a5/maps-compose/src/main/java/com/google/maps/android/compose/MapUpdater.kt#L72

I have a few suggestions:
1. Add additional field with current moving type
2. Add ability to call GoolgeMap instance from composable to allow users to subscribe necessary callbacks

**Comment by barbeau** [comment]
@egorikftp Thanks for the report! Agreed, this would be useful. We're actually already tracking this in issue https://github.com/googlemaps/android-maps-compose/issues/49, so please upvote that! I'm going to close this as a duplicate.
