### ISSUE TITLE
DisappearingScaleBar always aligns TopStart of screen

### ISSUE THREAD

**Issue by Priyankkjain** [googlemaps/android-maps-compose#165]
DisappearingScaleBar always aligns TopStart of the screen as the passed modifier with alignment goes to the inner ScaleBar. I think the modifier should belong to the AnimatedVisibility.

In this example even though the alignment is set to TopEnd, the DisappearingScaleBar will be displayed on TopStart.

```
Box(Modifier.fillMaxSize()) {

   GoogleMap (
     modifier = Modifier.matchParentSize(),
     cameraPositionState = cameraPositionState
   )

   DisappearingScaleBar(
    modifier = Modifier.align(Alignment.TopEnd).padding(top = 5.dp, end = 15.dp),
    cameraPositionState = cameraPositionState,
    textColor = state.textColor,
    lineColor = state.lineColor,
    shadowColor = state.shadowColor
  )
}
```

Although the workaround exists here, we just need to wrap the DisappearingScaleBar inside another layout and set alignment on that layout.

**Comment by barbeau** [comment]
@Priyankkjain Thanks for the report! I'll fix this shortly.
