### ISSUE TITLE
DisappearingScaleBar do not disappear after specified visibilityDurationMillis

### ISSUE THREAD

**Issue by Priyankkjain** [googlemaps/android-maps-compose#166]
The new DisappearingScaleBar does not disappear after the specified visibilityDurationMillis. Unless I have interpreted it wrong, I think what DisappearingScaleBar does is that it automatically disappears after specified visibilityDurationMillis on every zoom click.

But currently, after the initial disappearance that is not happening.

#### Steps to reproduce

  1. Add DisappearingScaleBar to map
  2. Wait for it to disappear for the first time
  3. Just press zoom in one time
  4. After the zoom in the scalebar does not automatically disappear.

I have also attached a video for the issue. It only contains the DisappearingScaleBar on top of the map.

https://user-images.githubusercontent.com/20212314/176884199-d9bc0e42-d426-453a-aaac-b967a6c3e2bc.mp4

. 

#### Code example
```
GoogleMap(
  modifier = Modifier.matchParentSize(),
  cameraPositionState = cameraPositionState,
  onMapLoaded = {
    isMapLoaded = true
  }
)
DisappearingScaleBar(
  modifier = Modifier
  .padding(top = 5.dp, end = 15.dp)
  .align(Alignment.TopStart),
  cameraPositionState = cameraPositionState,
  visibilityDurationMillis = 5_000
)
```

I think the issue lies in the LaunchedEffect of  DisappearingScaleBar. Because of the condition, it is not able to hide the scale bar after the time-out period.

**Comment by barbeau** [comment]
@Priyankkjain Thanks for the repro steps with the zoom button! That's very useful. And thanks for the PR https://github.com/googlemaps/android-maps-compose/pull/168 as well. Using pinch-to-zoom it's much harder to repro but it does seem to occasionally happen. I'll look at this further and see if you PR seems a reasonable way to fix this.
