### ISSUE TITLE
Fix flaky tests on CI

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-compose#174]
#### Steps to reproduce

Run the test workflow on `main` and notice that instrumentation tests are failing. Example failed runs:

https://github.com/googlemaps/android-maps-compose/runs/7306842111
https://github.com/googlemaps/android-maps-compose/runs/7283340731

Also see discussion in #171

#### Code example

N/A

#### Stack trace

```
com.google.maps.android.compose.MapInColumnTests > testScrollColumn_MapCameraRemainsSame[test(AVD) - 10] FAILED 
	java.lang.AssertionError: Assert failed: The component is displayed!
	at androidx.compose.ui.test.AssertionsKt.assertIsNotDisplayed(Assertions.kt:51)
```

**Comment by arriolac** [comment]
Looks like there are 2 causes for the failed actions linked in the description:

1. Failure due to secrets not being available on forks. This is the reason for the failed PR in https://github.com/googlemaps/android-maps-compose/runs/7283340731. This should be addressed by #175 
2. Failure in `MapInColumnTests.testScrollColumn_MapCameraRemainsSame`. This appears to be env specific as running it locally passes. Perhaps running the test on the same emulator might give us some hints on what might be causing the test failure.

**Comment by barbeau** [comment]
I tried running locally on this emulator and the tests still pass:

![image](https://user-images.githubusercontent.com/928045/178588913-65601e4e-29b6-4891-b8b9-94bf0776c615.png)

**Comment by wangela** [comment]
Tests cannot pass on PRs from forks. Root cause: https://github.com/community/community/discussions/50161
