### ISSUE TITLE
Add Street View Composable

### ISSUE THREAD

**Issue by CTaylorII** [googlemaps/android-maps-compose#177]
I could not find a JetPack Compose documentation nor code for working with the Google Maps Stretview. I only see Fragments or old school views.  Can you provide a Compose StreetView component? 

Thanks

**Comment by arriolac** [comment]
Happy to take this one. Thanks for raising @CTaylorII

**Comment by CTaylorII** [comment]
Wow! Awesome! Thanks for putting in this functionality :)
