### ISSUE TITLE
Artifacts for latest Maps Compose versions not available on Maven Repositories

### ISSUE THREAD

**Issue by jrgonzalezg** [googlemaps/android-maps-compose#194]
Hi!,

the GitHub page for Maps Compose refers to version 2.7.0 and there seems to also be a 2.6.0 version before that one but none of them seem to have its artifacts published to a Maven Repo.

The last version available on Maven Central seems to be 2.5.3 for instance (see https://search.maven.org/search?q=maps-compose). I also tried using the Google repository but that did not work either.

Are the newer versions available on some other Maven repo or was there an issue publishing them?

Thanks!

**Comment by arriolac** [comment]
@wangela can you help here?

**Comment by wangela** [comment]
[v2.6.0](https://github.com/googlemaps/android-maps-compose/releases/tag/v2.6.0) and [v2.7.0](https://github.com/googlemaps/android-maps-compose/releases/tag/v2.7.0) have been released to Maven! Thanks for reporting and sorry for the delay as we debug our release workflow.

- https://repo1.maven.org/maven2/com/google/maps/android/maps-compose/
- https://repo1.maven.org/maven2/com/google/maps/android/maps-compose-widgets/
