### ISSUE TITLE
GoogleMap Compose view is drawn outside of clipping area

### ISSUE THREAD

**Issue by ptornhult** [googlemaps/android-maps-compose#199]
It seems the GoogleMap composable view doesn't fully respect the parent nor its own clip area (unless there is a background). 

Version: 2.5.0 of com.google.maps.android:maps-compose
Android 12

#### Steps to reproduce

  1. Put a GoogleMap inside a Card or Dialog with rounded corners where the map fills out to each side. The map will be drawn outside of the rounded corners where there is no background layer, no matter if you put Modifier.clip on the map itself or the parent Composable.

#### Code example

```
Card(modifier = Modifier
        .fillMaxWidth()
        .clip(RoundedCornerShape(24.dp))) {
        GoogleMap(
            modifier = Modifier
                .fillMaxWidth()
                .clip(RoundedCornerShape(24.dp)),
            uiSettings = MapUiSettings(),
            properties = MapProperties(),
            cameraPositionState = CameraPositionState(),
            contentPadding = PaddingValues(20.dp),
        )
    }
```

Here is an example from a Dialog with the same corner radius. Clipping can be seen as working at the bottom of the map, but on the top the map, content is drawn outside of the dialog. I put in some padding on the top of the map to show that there is some kind of clipping but it's still spilling out behind the dialog
![image](https://user-images.githubusercontent.com/1590380/189371139-6fac0074-8f1b-4129-a090-0ffe1f8686d9.png)

**Comment by mrmar096** [comment]
Hey man,

Try adding shape directly to the Card element and you won't need any clip. Something like this:
```kotlin 
Card(
    modifier = Modifier
        .height(180.dp),
    shape = RoundedCornerShape(8.dp)
) {
    val cameraPositionState = rememberCameraPositionState {
        position = CameraPosition.fromLatLngZoom(location, 13f)
    }
    GoogleMap(
        modifier = Modifier.fillMaxSize(),
        cameraPositionState = cameraPositionState
    ) {
        Marker(
            state = MarkerState(position = location),
            title = "Singapore",
            snippet = "Marker in Singapore"
        )
    }
}
}
```

**Comment by ptornhult** [comment]
> Hey man,
> 
> Try adding shape directly to the Card element and you won't need any clip. Something like this:
> 
> ```kotlin
> Card(
>     modifier = Modifier
>         .height(180.dp),
>     shape = RoundedCornerShape(8.dp)
> ) {
>     val cameraPositionState = rememberCameraPositionState {
>         position = CameraPosition.fromLatLngZoom(location, 13f)
>     }
>     GoogleMap(
>         modifier = Modifier.fillMaxSize(),
>         cameraPositionState = cameraPositionState
>     ) {
>         Marker(
>             state = MarkerState(position = location),
>             title = "Singapore",
>             snippet = "Marker in Singapore"
>         )
>     }
> }
> ```

Thanks, that worked. Think this can be closed 👍

**Comment by nikonhub** [comment]
I'm still having the issue with rounded corners.

When GoogleMap is in :

- Main hierarchy : GoogleMap litemode (true or false) with clipped rounded corners OK

- Inside a Dialog :  litemode false clipped corners doesn't work. (litemode true ok)

- Inside a Popup : Corners OK, but unusable because very laggy
