### ISSUE TITLE
Basic things don't work

### ISSUE THREAD

**Issue by nowiwr01w** [googlemaps/android-maps-compose#204]
Google,
- your demo app doesn't work
- marker onClick method doesn't work

Google, you're a multi-billion dollar corporation and you can't afford two Hindus to come and solve all your problems?
Hindus are great people, I always rejoice when I find the right answers in their YouTube videos. No offense to anyone. BUT Google????

1) 
- implementation 'com.google.maps.android:maps-compose:2.5.3'
- implementation 'com.google.android.gms:play-services-maps:18.1.0'
2) 
- compileSdk 33, minSdk 26, targetSdk 33
- Pixel 4a Emulator
- macOS Monterey 12.5 with Apple M1 Max

1) Your demo app doesn't work:
- clone 
- build
- run
- click any button

expected: I can see Basic Map, Map in Column and so on
real: nothing happens, just progress bar

2)  Marker onClick method doesn't work
```kotlin
@Composable
fun MapContent(city: City) {
    val singapore = LatLng(city.latitude, city.longitude)
    val cameraPositionState = rememberCameraPositionState {
        position = CameraPosition.fromLatLngZoom(singapore, 12f)
    }
    GoogleMap(
        modifier = Modifier.fillMaxSize(),
        cameraPositionState = cameraPositionState,
        uiSettings = MapUiSettings(zoomControlsEnabled = false)
    ) {
        Marker(
            state = MarkerState(position = singapore),
            onClick = {
                Timber.tag("Zhopa").d("click")
                true
            }
        )
    }
}
```
expected: some "click" words in Log
real: nothing

Google????

**Comment by nowiwr01w** [comment]
Google?

**Comment by wangela** [comment]
Closing this due to violation of this repository's [Code of Conduct](https://github.com/googlemaps/android-maps-compose/blob/main/CODE_OF_CONDUCT.md). Please re-open when you have edited [the first comment](https://github.com/googlemaps/android-maps-compose/issues/204#issue-1381521770) to remove discriminatory references to a group of people.

**Comment by nowiwr01w** [comment]
Google?
