### ISSUE TITLE
App crashes on bottom nav due to a fix on version 2.7.2  mapView.onDestroy(), mapView.removeAllViews()

### ISSUE THREAD

**Issue by thekingrenz23** [googlemaps/android-maps-compose#207]
#### Environment details

1. com.google.maps.android:maps-compose:2.7.2

#### Steps to reproduce

  1. Clone this [repo](https://github.com/thekingrenz23/GoogleMapsBottomNav)
  2. add your google api key to the manifest file
  3. Build the app
  4. Quickly navigate between the bottom tabs and check if the app will crash or not
  5. The app crashes big time

### Sample Video
1. https://streamable.com/cbtdhq

#### Stack trace
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.googlemapsbottomnav, PID: 3421
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bq.z()' on a null object reference
        at com.google.maps.api.android.lib6.impl.cv.l(:com.google.android.gms.dynamite_mapsdynamite@223017067@22.30.17 (100408-0):0)
        at com.google.android.gms.maps.internal.q.ba(:com.google.android.gms.dynamite_mapsdynamite@223017067@22.30.17 (100408-0):2)
        at et.onTransact(:com.google.android.gms.dynamite_mapsdynamite@223017067@22.30.17 (100408-0):4)
```

#### Observation
The app will not crash when it use the com.google.maps.android:maps-compose:2.7.0 version

**Comment by thekingrenz23** [comment]
@wangela @polivmi1

**Comment by polivmi1** [comment]
@thekingrenz23 I see that you are using nested navigation for each screen composable, which is causing the problem.

If you use this I am not able to reproduce:

```
AnimatedNavHost(
            navController = navController,
            startDestination = Screen.Other.route
        ) {
                composable(
                    route = Screen.Map.route
                ) {
                    MapRoute()
                }
                composable(
                    route = Screen.Other.route
                ) {
                    OtherRoute()
            }
}
```
The crash does happen during onStart and will be most likely related to caching. I can dig more later.

**Comment by thekingrenz23** [comment]
Any update?

**Comment by wangela** [comment]
@thekingrenz23 Did you try adjusting the architecture as @polivmi1 suggested?

**Comment by thekingrenz23** [comment]
> @thekingrenz23 Did you try adjusting the architecture as @polivmi1 suggested?

Are you kidding ? Bruh I need the nested navigation How can I handle complex routes 🤣

**Comment by thekingrenz23** [comment]
and also the code that @polivmi1 gave is not a suggestion its a conclusion that it only happens on nested nav graph LOL

**Comment by thekingrenz23** [comment]
@polivmi1 update ?

**Comment by thekingrenz23** [comment]
If you dont have a solution please just remove it. It will crash my app for future releases

**Comment by polivmi1** [comment]
@thekingrenz23 I hope that you can stay on the older version for a while unless we resolve this. I am trying to help and look at this, but I am also working, so I don't have that much free time.
@wangela would you be able to see where exactly in the obfuscated google maps code this is crashing? It does so during the start, so there must be some lifecycle caching during nested navigation and when switching navigation and destroying the view, google maps internally thinks something is still available. It could also be some race condition when it is destroyed and started again.

**Comment by thekingrenz23** [comment]
Any updates ?
