### ISSUE TITLE
Basic things don't work

### ISSUE THREAD

**Issue by nowiwr01w** [googlemaps/android-maps-compose#208]
Google,
- your demo app doesn't work
- marker onClick method doesn't work

1) 
- implementation 'com.google.maps.android:maps-compose:2.5.3'
- implementation 'com.google.android.gms:play-services-maps:18.1.0'
2) 
- compileSdk 33, minSdk 26, targetSdk 33
- Pixel 4a Emulator
- macOS Monterey 12.5 with Apple M1 Max

1) Your demo app doesn't work:
- clone 
- build
- run
- click any button

expected: I can see Basic Map, Map in Column and so on
real: nothing happens, just progress bar

2)  Marker onClick method doesn't work
```kotlin
@Composable
fun MapContent(city: City) {
    val singapore = LatLng(city.latitude, city.longitude)
    val cameraPositionState = rememberCameraPositionState {
        position = CameraPosition.fromLatLngZoom(singapore, 12f)
    }
    GoogleMap(
        modifier = Modifier.fillMaxSize(),
        cameraPositionState = cameraPositionState,
        uiSettings = MapUiSettings(zoomControlsEnabled = false)
    ) {
        Marker(
            state = MarkerState(position = singapore),
            onClick = {
                Timber.tag("Zhopa").d("click")
                true
            }
        )
    }
}
```
expected: some "click" words in Log
real: nothing

**Comment by nowiwr01w** [comment]
Google?

**Comment by nowiwr01w** [comment]
Google?

**Comment by polivmi1** [comment]
@nowiwr01w have you added an API key?

**Comment by nowiwr01w** [comment]
@polivmi1 sure

**Comment by wangela** [comment]
Can't reproduce. @nowiwr01w Please make sure you have followed the instructions in the [README](https://github.com/googlemaps/android-maps-compose#readme). If after that you still do not see the screen, please provide the error message from the Log in any future bug reports.
