### ISSUE TITLE
GoogleMap Composable breaks layout in Preview

### ISSUE THREAD

**Issue by claytongreen** [googlemaps/android-maps-compose#212]
A previous issue #128 and pull request #179 fix the Compose preview breaking when using a `GoogleMap` composable.
But the layout in the preview is still incorrect as any of the modifiers passed to the `GoogleMap` are discarded with the early return.

For example:

```kotlin
Column(Modifier.fillMaxSize()) {
    GoogleMap(Modifier.weight(1f))
    SomeExampleContent()
}
```

![result](https://user-images.githubusercontent.com/3336370/196565891-dec0f33d-89b0-4180-878e-c885d8fec8d6.png)

A possible fix could be instead of a bare return when in preview, `GoogleMap` could return a `Box` that keeps the modifiers.
```kotlin
// When in preview, early return a Box with the received modifier preserving layout
if (LocalInspectionMode.current) {
    return Box(modifier = modifier)
}
```

I have a commit (7e103f584cf44bda8ceff47706e2578d811d943d) ready to go, but the pull request said to make an issue first.

Thanks

**Comment by arriolac** [comment]
@claytongreen that's how I would fix it, too. Feel free to open a pull request with that fix.

**Comment by wangela** [comment]
Since this changes the return type, do users of this library have to change their code when using the GoogleMap composable? i.e., is it a breaking change?

**Comment by arriolac** [comment]
Ah yeah it should be:

```
// When in preview, early return a Box with the received modifier preserving layout
if (LocalInspectionMode.current) {
    Box(modifier = modifier)
    return
}
```

**Comment by claytongreen** [comment]
Good catch!
Change has been pushed
