### ISSUE TITLE
MarkerState behaves in a non-@Stable manner at runtime

### ISSUE THREAD

**Issue by bubenheimer** [googlemaps/android-maps-compose#232]
Maps Compose 2.7.2

Using `MarkerState` as a Composable function parameter appears to render the function effectively non-skippable at runtime. I suspect that this is due to unstable `LatLng` `MarkerState.position`.

I'd think that explicitly marking `MarkerState` `@Stable` would easily and validly avoid this issue.

The function below recomposes whenever its parent recomposes, even when keeping MarkerState unchanged:

```
@Composable
fun Foo(markerState: MarkerState) {
    println("${markerState.position} - ${markerState.dragState}")
}
```

**Comment by DSteve595** [comment]
Good find! The cause is actually the `var marker: Marker?` property. A similar improvement can be made to `CameraPositionState`. Will fix.
