### ISSUE TITLE
Docs request: compose marker clustering guide

### ISSUE THREAD

**Issue by wangela** [googlemaps/android-maps-compose#255]
A guide and sample code for how to implement marker clustering with android-maps-compose would be really helpful, especially once Issue #44 is addressed. This might be too big for the README, so might live better at the Maps Compose documentation on [developers.google.com.](https://developers.google.com/maps/documentation/android-sdk/maps-compose)

**Comment by barbeau** [comment]
This can be based on the existing minimal sample here:
https://github.com/googlemaps/android-maps-compose#obtaining-access-to-the-raw-googlemap-experimental

**Comment by wangela** [comment]
New sample app published with #44 at https://github.com/googlemaps/android-maps-compose/blob/main/app/src/main/java/com/google/maps/android/compose/MapClusteringActivity.kt

**Comment by wangela** [comment]
Ah, this was also fixed by #44 in the README at https://github.com/googlemaps/android-maps-compose#clustering
