### ISSUE TITLE
Text is different than on iOS or Javascript, looks streched

### ISSUE THREAD

**Issue by ivannarino** [googlemaps/android-maps-compose#291]
#### Environment details

Pixel 6a, Android 13
Maps compose: 2.10.0
Using Google Play Services Maps "18.1.0"
Google Play Services version on the device: 34.7.10-21 [0] [PR] 512129822
Android SDK Version: compile SDK 33

#### Steps to reproduce

  1. Display the SDK maps
  2. Zoom on any area that has POIs

#### Output

On the right is the android compose sample app. The text looks stretched.

![image](https://user-images.githubusercontent.com/5160934/224682769-4d751fe2-12df-4a6c-b1e3-66df62a1f439.png)

This also happens using the XML/Fragment version of the library.

There is an issue on the issue tracker that mentions this https://issuetracker.google.com/issues/271731840

**Comment by DSteve595** [comment]
This isn't something that's controllable via this library. According to the response on the issue tracker, this is working as intended. I suspect it's just the reality of having different text rendering systems on each platform.
