### ISSUE TITLE
Implement custom info windows

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-compose#3]
**Is your feature request related to a problem? Please describe.**
Custom info windows cannot be implemented at the moment.

 **Describe the solution you'd like**
`setInfoWindowAdapter` should be exposed on the `GoogleMap` or `Marker` composable. The implementation should allow using Compose for setting the content or info window vs. having to use Views.

**Comment by arriolac** [comment]
Proposed API:
```kotlin
Marker(
  position = LatLng(0.0f, 0.0f),
  title = "Marker with custom info window",
  infoWindowContent = { marker ->
    Box(modifier = Modifier.fillMaxSize()) {
      Text(marker.title ?: "Title")
     }
   },
   infoWindow = { marker ->
     // ...return a Composable
   }
)
```

**Comment by webfrea-k** [comment]
Hello @arriolac, is there a snapshot version with this feature already in (or a different repo)?
Thank you 😊
