### ISSUE TITLE
Prevent Maps Compose elements from being used outside of MapApplier's scope

### ISSUE THREAD

**Issue by kozaxinan** [googlemaps/android-maps-compose#30]
At the moment, GoogleMap composable methods are basic composable method that can be called from any composable.
They dont work outside of the GoogleMap composable. It would be better to have GoogleMapScope interface like ColumnScope, RowScope. And all of GoogleMap methods could be methods of GoogleMapScope and it would be easier to find methods and prevent making mistakes.

**Comment by arriolac** [comment]
I am waiting for the [ComposableTarget](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/runtime/runtime/src/commonMain/kotlin/androidx/compose/runtime/ComposableTarget.kt?q=ComposableTarget&ss=androidx%2Fplatform%2Fframeworks%2Fsupport) annotation class to be released which will prevent invocation of Google Map elements outside of `MapApplier`. My original design used this technique but `ComposableTarget` is much preferable. The next compiler plugin containing this change might be able to infer the target automatically but we will need to wait until it is released.

**Comment by kozaxinan** [comment]
ComposableTarget looks interesting. I hope compiler and IDE will understand in perfectly. Without any scope or heritage, currently all methods look same and it confused developer.

**Comment by arriolac** [comment]
Done in #130. It'll be part of the next Maps Compose release
