### ISSUE TITLE
Animated tile/ground overlay

### ISSUE THREAD

**Issue by webfrea-k** [googlemaps/android-maps-compose#34]
What is the recommended way for overlay animations?
Before I would create 10 `Ground/Tile` overlay objects, add them to map and while I'd keep a reference to each one, I'd change `transparency` property in a loop (in each loop iteration I would hide all but one).

I've tried something like this:

```
GoogleMap(
/*settings*/
) {
    val currentVisibleIndex: Int by vm.visibleIndex.collectAsState()
    tileOverlays.forEachIndexed { index, tile ->
        TileOverlay(..., transparency = index == currentVisibleIndex)
    }
}
```

It works okay-ish if you don't move around on the map (or zoom in and out), if you change the camera, the entire `GoogleMap {}` get's recomposed and this causes lagging as all the tile overlays are re-added to the map (`tileOverlay.forEachIndexed` above is executed again).
What can I do to achieve smooth animation?
Thanks.

**Comment by arriolac** [comment]
The code snippet you shared looks fine to me. Did you test this on a release build? Animations on debug builds can be very slow but is a non-issue in production/release builds

**Comment by webfrea-k** [comment]
It works well. Thank you @arriolac
