### ISSUE TITLE
Cluster does not get removed

### ISSUE THREAD

**Issue by cwsiteplan** [googlemaps/android-maps-compose#397]
I conditionally show clusters in the map.
It seems once a cluster is added it won't get removed.

```
    var showCluster by remember { mutableStateOf(false) }

GoogleMap(...) {
  if (showCluster) {
    Clustering(...)
  }
  // other clusters
  Clustering(...)
}
```

Adapted the sample to have multiple clusters that can be toggled on/off
https://gist.github.com/cwsiteplan/5e78d6068d81200421a8a74c161991a1#file-maps-compose-cluster-bug-kt

**Comment by cobermayr** [comment]
I experienced the same problem.

**Comment by cwsiteplan** [comment]
seems to work fine now - will close
