### ISSUE TITLE
4.3.3 not on MvnRepository

### ISSUE THREAD

**Issue by cf256** [googlemaps/android-maps-compose#524]
Latest version is 4.3.2: https://central.sonatype.com/artifact/com.google.maps.android/maps-compose?smo=true, https://mvnrepository.com/artifact/com.google.maps.android/maps-compose

However latest GitHub release is 4.3.3

**Comment by risalfajar** [comment]
Thanks, just confused of why my imports doesn't work

**Comment by kungufli** [comment]
The issue is now fixed.

**Comment by wangela** [comment]
Sorry for the delay folks! Our automated release process broke down and we had to manually release the artifact.
