### ISSUE TITLE
fix:  update set() to update() for a ComposeNode (map objects)

### ISSUE THREAD

**Issue by el-qq** [googlemaps/android-maps-compose#547]
**Is your feature request related to a problem? Please describe.**
For map objects (e.g., `Circle()`), parameters are created both in `factory` and in the `update` block

```kotlin

    ComposeNode<CircleNode, MapApplier>(
        factory = {
            val circle = mapApplier?.map?.addCircle {
                center(center)
                 //...
            } ?: error("Error adding circle")
            circle.tag = tag
            CircleNode(circle, onClick)
        },
        update = {
            update(onClick) { this.onCircleClick = it }

            set(center) { this.circle.center = it }

```

In addition, `update()` is recommended. From the description: 
```For example, use [update} when value is passed into the class constructor parameters.```

 **Describe the solution you'd like**

```kotlin

//....
        update = {
            update(onClick) { this.onCircleClick = it }

            update(center) { this.circle.center = it }

```

**Comment by bubenheimer** [comment]
I'd call this a bug, not a feature request. Affected code uses the wrong operator, causing slower performance.
