### ISSUE TITLE
Please revert "jvmTarget" to 1.8 or 11

### ISSUE THREAD

**Issue by hoc081098** [googlemaps/android-maps-compose#599]
**Is your feature request related to a problem? Please describe.**

My app is targeting java 1.8. When updating to version 6.0.0, I cannot build app anymore.
```
> Task :app:writeDebugSigningConfigVersions
e: file:///home/runner/work/Maps-Jetpack-Compose/Maps-Jetpack-Compose/app/src/main/java/com/hoc081098/mapscompose/presentation/markers/MarkersScreen.kt:53:29 Cannot inline bytecode built with JVM target 17 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option.

> Task :app:compileDebugKotlin FAILED
```

----

 **Describe the solution you'd like**

Revert "jvmTarget" to 1.8 or 11.

----

 **Additional context**

There is no reason to change it to 17.

**Comment by el-qq** [comment]
#600

**Comment by hoc081098** [comment]
Thank @el-qq 🙏

**Comment by hoc081098** [comment]
Close this via https://github.com/googlemaps/android-maps-compose/releases/tag/v6.1.0
