### ISSUE TITLE
Custom InfoWindow when using MarkerComposable

### ISSUE THREAD

**Issue by mariohide** [googlemaps/android-maps-compose#616]
Now that we have `MarkerComposable`, which allows us to create fully custom-styled markers, and `MarkerInfoWindow`, which allows us to create fully custom-styled InfoWindows, how should I proceed if I want both the Marker and InfoWindow to have custom styles?

**Comment by NavorJames** [comment]
How come this not yet implemented. There is already a composable that supports Composable Marker and one that supports Composable InfoWindow. Why not both?

**Comment by mariohide** [comment]
duplicate: https://github.com/googlemaps/android-maps-compose/issues/383
fixed: https://github.com/googlemaps/android-maps-compose/pull/384
