### ISSUE TITLE
Updating MarkerState position can lead to error 

### ISSUE THREAD

**Issue by NitroG42** [googlemaps/android-maps-compose#99]
I feel link there is a missing behavior with the rememberMarkerState() function.

Here's a code sample : 

#### Code example

```
@Composable
fun Maps() {
    val cameraPositionState = rememberCameraPositionState {}

    var projectionCenter by remember {
        mutableStateOf<LatLng?>(null)
    }

    LaunchedEffect(cameraPositionState.position) {
        val projection = cameraPositionState.projection
        if (projection != null) {
            val bounds = projection.visibleRegion.latLngBounds
            projectionCenter = bounds.center
        }
    }
    GoogleMap(
        cameraPositionState = cameraPositionState,
        modifier = Modifier.fillMaxSize()
    ) {
        projectionCenter?.let {
            Marker(
                state = rememberMarkerState(key = "center", position = it),
                icon = BitmapDescriptorFactory.defaultMarker(),
            )
        }
    }
}
```

This code should display a marker at the center of the projection, even if you move. 
It won't work, because the marker position is remembered once : ` rememberMarkerState(key = "center", position = it)`, then it won't be updated unless you call MarkerState.position = newPosition.

With the following change, the code works : 
```
projectionCenter?.let { latLng ->
            Marker(
                state = rememberMarkerState(key = "center", position = latLng).also { 
                    position = latLng 
                },
                icon = BitmapDescriptorFactory.defaultMarker(),
            )
        }
```

It is the expected behavior? 
I'm afraid some people like me search for some times why their code is not working.
I think `rememberMarkerState(position = newPosition)` should updated the underlying markerState if it's already remembered, but maybe I'm wrong?

One last info : with one marker the use case is trivial, I can just do that to fix the code :
```
@Composable
fun Maps() {
    val cameraPositionState = rememberCameraPositionState {}

    val projectionCenter = rememberMarkerState()

    LaunchedEffect(cameraPositionState.position) {
        val projection = cameraPositionState.projection
        if (projection != null) {
            val bounds = projection.visibleRegion.latLngBounds
            projectionCenter.position = bounds.center
        }
    }
    GoogleMap(
        uiSettings = MapUiSettings(mapToolbarEnabled = false, myLocationButtonEnabled = false, zoomControlsEnabled = false),
        cameraPositionState = cameraPositionState,
        modifier = Modifier.fillMaxSize()
    ) {
        Marker(
            state = projectionCenter,
            icon = BitmapDescriptorFactory.defaultMarker(),
        )
    }
}
```
But I think the issue arise with a dynamic list, where it becomes hard to track the change of a specific marker.
My first test was using a mutableStateListOf()

**Comment by arriolac** [comment]
Based on your 1st snippet, the behavior you noticed is working as expected. Calling `rememberMarkerState(key = "center", position = it)` multiple times won't trigger recomposition since the key stays the same. Either use `rememberMarkerState` and store it as a variable (as you have it in your last snippet), or construct a `MarkerState(position)` directly.

**Comment by NitroG42** [comment]
That's what I thought first, But using a "dynamic key" (using the latlng in it) still won't trigger recomposition:
```
@Composable
fun Maps() {
    val cameraPositionState = rememberCameraPositionState {}

    var projectionCenter by remember {
        mutableStateOf<LatLng?>(null)
    }

    LaunchedEffect(cameraPositionState.position) {
        val projection = cameraPositionState.projection
        if (projection != null) {
            val bounds = projection.visibleRegion.latLngBounds
            projectionCenter = bounds.center
        }
    }
    val center = projectionCenter
    GoogleMap(
        uiSettings = MapUiSettings(mapToolbarEnabled = false, myLocationButtonEnabled = false, zoomControlsEnabled = false),
        cameraPositionState = cameraPositionState,
        modifier = Modifier.fillMaxSize()
    ) {
        if (center != null) {
            Marker(
                state = rememberMarkerState(
                    key = "${center.latitude} ${center.longitude}", position = center
                ),
                icon = BitmapDescriptorFactory.defaultMarker(),
            )
        }
    }
}
```
result :
![markerstate](https://user-images.githubusercontent.com/1549495/164397156-81f592c9-ab3a-4741-864f-1677ac419457.gif)

But I didn't know about using directly MarkerState (I wrongly read that it was internal but of course it's not !), so that might be the best solution.
(with the above snippet, using `state = MarkerState(center),` produce the right behavior of course)

Anyway, I think my issue with understanding is more with how `rememberSaveable` works and less with Compose Maps libs. I remember reading some question that were similar to mine.

I think the `key` changing without the MarkerState updating might still be an issue, I'll check with the Kotlin Compose Slack and will close the issue if it's linked to `rememberSaveable` behavior.

**Comment by NitroG42** [comment]
Actually it's a bug in Compose since 2020 -> https://issuetracker.google.com/issues/152014032

**Comment by Sergiyss** [comment]
Is the question still open? Help me. the last Polyline is not updated, but markers are drawn according to the route.

**Comment by jakepurple13** [comment]
I was having this same exact issue, however, I noticed that the `rememberMarkerState` wasn't making use of the `rememberSaveable` `inputs` at all! It is only changing the key if the key gets changed. So this would never recompose!

I believe the fix wanted would be this:
```kotlin
@Composable
public fun rememberMarkerState(
    key: String? = null,
    position: LatLng = LatLng(0.0, 0.0),
): MarkerState = rememberSaveable(inputs = arrayOf(position), key = key, saver = MarkerState.Saver) {
    MarkerState(position)
}
```
